### ISSUE TITLE
yolov3 pascal voc weights

### ISSUE THREAD

**Issue by mouad47** [cowarder/yolov3_voc#1]
hello @cowarder 
it's not an issue, I'm sorry for that
but l need the final model that you trained on voc (model_scratch),can you upload it please !
thank you

**Comment by cowarder** [comment]
Hi @mouad47 , you can try [this,](https://drive.google.com/file/d/1JPKNRh6s-URed5bhyXpmzaYFwCxTksQo/view?usp=sharing) and change the name in code

**Comment by mouad47** [comment]
thank you so much @cowarder

**Comment by mouad47** [comment]
@cowarder can you mention the dependencies, I've got an error !

**Comment by cowarder** [comment]
@mouad47 you can paste your error log here.
